git config --global 'alias.s' 'status'
git config --global 'alias.br' 'branch'
git config --global 'alias.pl' 'pull --ff-only'
git config --global 'alias.last' 'log -1'
git config --global 'alias.tree' 'log --graph --pretty=oneline --abbrev-commit'
